### ISSUE TITLE
ZMQ::Socket#send_messages hangs up

### ISSUE THREAD

**Issue by k-solutions** [crystal-community/zeromq-crystal#2]
In your Publish - Subscribe example if I change #52 

```
topic, body, identity = s4.receive_strings
```

script hangs up

**Comment by benoist** [comment]
The messages are already fetched on line #50.
Doing it again on #52 will wait for new messages, but they will never be send.

**Comment by k-solutions** [comment]
I think it hangs right in the receive_messages method, probably in the while loop, even when I do pass  ZMQ::DONTWAIT it still hangs up

**Comment by benoist** [comment]
There was a problem with the more parts, it always returned a truthy value instead of a correct boolean. This is now fixed and the example works as expected.

Thanks!

**Comment by k-solutions** [comment]
Thank you for the fast commit ...
Would you consider to have some kind of buffer overflow in receive_messages as MESSAGES_MAX_NMB which escape from loop or it would delegate this role in some higher level API ?

**Comment by benoist** [comment]
never thought about it really, I don't really know what the use case would be to send a lot of messages in one go. I thought that ZeroMQ allows multiple message mainly for routing information so that you can send replies to the original sender. If you want to bundle information it might be better to just encode it in something like json.
But if you know a use case for it then it might be a worthy addition. :)

**Comment by k-solutions** [comment]
I follow 0mq  examples and would plan to add some of them to your example list and there with Proxy/Device ROUTER - DEALER connections we may have a use case for it :)

**Comment by benoist** [comment]
Ok, yes routing information is required for those socket types.
Thank you very much for helping with that! Please feel free to add your name to the contributors list in your next PR :)

**Comment by k-solutions** [comment]
Thank you
